name: Integration Tests

on:
  pull_request:
    branches:
      - ntrujillo/main
  workflow_dispatch:

jobs:
  android-tests:
    name: Run Android Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0

      - name: Install dependencies
        run: flutter pub get

      - name: Install Android Command Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          mkdir -p $HOME/.android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          unzip -q commandlinetools.zip -d $HOME/.android-sdk/cmdline-tools
          mv $HOME/.android-sdk/cmdline-tools/cmdline-tools $HOME/.android-sdk/cmdline-tools/latest

      - name: Configure Android SDK Paths
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/.android-sdk" >> $GITHUB_ENV
          echo "PATH=$HOME/.android-sdk/cmdline-tools/latest/bin:$HOME/.android-sdk/emulator:$HOME/.android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "Current ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"

      - name: Accept Android SDK Licenses
        run: |
          echo "Accepting Android SDK licenses..."
          yes | sdkmanager --licenses

      - name: Install Emulator and System Images
        run: |
          sdkmanager --verbose --install "system-images;android-30;google_apis;x86_64" "platforms;android-30" "platform-tools" "emulator"

      - name: Set up KVM for Emulator
        run: |
          echo "Checking and configuring KVM for Android Emulator..."
          if grep -q "kvm" /etc/group; then
            echo "Group 'kvm' already exists. Adding user to 'kvm' group."
          else
            echo "Creating 'kvm' group."
            sudo groupadd kvm
          fi
          sudo gpasswd -a $USER kvm
          ls -la /dev/kvm || echo "KVM device not found. Emulation might not use hardware acceleration."

      - name: Set up Android Emulator
        run: |
          source $GITHUB_ENV
          echo "Creating AVD with explicit ABI..."
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --abi "x86_64" --device "pixel" || (
            echo "AVD creation failed. Debugging directory structure..."
            ls -R $ANDROID_SDK_ROOT/system-images
            exit 1
          )
          nohup emulator -avd test -no-audio -no-window -gpu swiftshader_indirect &
          timeout 120s adb wait-for-device

      - name: Run Android Integration Tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --device-id=emulator-5554
