name: Integration Tests

on:
  pull_request:
    branches:
      - ntrujillo/main
  workflow_dispatch:


jobs:
  android-tests:
    name: Run Android Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0
      - name: Install dependencies
        run: flutter pub get

      - name: Run Android integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
    
  ios-tests:
    name: Run IOS Integration Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0 

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: pod install --project-directory=ios

      - name: Run iOS integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
      
      
