name: Integration Tests with Software Rendering

on:
  pull_request:
    branches:
      - ntrujillo/main
  workflow_dispatch:

jobs:
  android-tests:
    name: Run Android Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0

      - name: Install dependencies
        run: flutter pub get

      - name: Install Android Command Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
          sudo unzip -q commandlinetools.zip -d /usr/lib/android-sdk/cmdline-tools
          sudo mv /usr/lib/android-sdk/cmdline-tools/cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest

      - name: Configure Android SDK Paths
        run: |
          echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=/usr/lib/android-sdk/cmdline-tools/latest/bin:/usr/lib/android-sdk/emulator:/usr/lib/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV

      - name: Accept Android SDK Licenses
        run: |
          yes | sdkmanager --licenses || echo "Licenses accepted"

      - name: Install Emulator and System Images
        run: |
          echo "Installing emulator and system images..."
          sdkmanager --verbose "system-images;android-30;google_apis;x86_64" "platforms;android-30" "platform-tools" "emulator"

      - name: Debug Installed System Images
        run: |
          echo "Listing installed system images..."
          sdkmanager --list | grep "system-images"
          echo "Checking system-images directory..."
          ls -R $ANDROID_SDK_ROOT/system-images || echo "System images directory not found"

      - name: Force Install System Images
        run: |
          echo "Reinstalling system images to avoid corruption..."
          yes | sdkmanager --licenses
          sdkmanager --install "system-images;android-30;google_apis;x86_64"
          echo "Verifying system images installation..."
          ls -R $ANDROID_SDK_ROOT/system-images/android-30/google_apis/x86_64 || echo "System image directory not found"

      - name: Set up Android Emulator with Software Rendering
        run: |
          echo "Creating and starting the emulator..."
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          nohup emulator -avd test -no-audio -no-window -gpu swiftshader_indirect &
          timeout 120s adb wait-for-device

      - name: Verify Emulator State
        run: |
          echo "Verifying emulator state..."
          adb devices

      - name: Run Android Integration Tests
        run: |
          echo "Running Flutter integration tests..."
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --device-id=emulator-5554
