name: Run Integration Tests with Firebase Test Lab

on:
  push:
    branches:
      - ntrujillo/main
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Build APK for Testing
      run: flutter build apk --debug

    - name: Authenticate with Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > $HOME/firebase_key.json
        export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase_key.json
        gcloud auth activate-service-account --key-file=$HOME/firebase_key.json
        gcloud config set project integration-test-tutoria-9b3fe

    - name: Upload APK to Firebase Test Lab
      run: |
        gcloud firebase test android run \
          --type instrumentation \
          --app build/app/outputs/flutter-apk/app-debug.apk \
          --test build/app/outputs/flutter-apk/app-debug-androidTest.apk

    - name: Cleanup Firebase Key
      run: rm $HOME/firebase_key.json
