name: Integration Tests

on:
  pull_request:
    branches:
      - ntrujillo/main
  workflow_dispatch:

jobs:
  android-tests:
    name: Run Android Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0

      - name: Install dependencies
        run: flutter pub get

      - name: Set up Android Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y lib32stdc++6 qemu-kvm android-sdk
          sdkmanager "system-images;android-30;default;x86_64" "platforms;android-30" "platform-tools"
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;default;x86_64"
          nohup emulator -avd test -no-audio -no-window &
          adb wait-for-device

      - name: Run Android integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --device-id=emulator-5554

  ios-tests:
    name: Run IOS Integration Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        run: pod install --project-directory=ios

      - name: Start iOS Simulator
        run: |
          xcrun simctl boot "iPhone 14"
          xcrun simctl list devices

      - name: Run iOS integration tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --device-id="booted"
