name: Integration Tests

on:
  pull_request:
    branches:
      - ntrujillo/main
  workflow_dispatch:

jobs:
  android-tests:
    name: Run Android Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0

      - name: Install dependencies
        run: flutter pub get

      - name: Install Android Command Line Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O commandlinetools.zip
          sudo mkdir -p /usr/lib/android-sdk/cmdline-tools
          sudo unzip -q commandlinetools.zip -d /usr/lib/android-sdk/cmdline-tools
          sudo mv /usr/lib/android-sdk/cmdline-tools/cmdline-tools /usr/lib/android-sdk/cmdline-tools/latest

      - name: Configure Android SDK Paths
        run: |
          echo "ANDROID_SDK_ROOT=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "PATH=/usr/lib/android-sdk/cmdline-tools/latest/bin:/usr/lib/android-sdk/emulator:/usr/lib/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "Current ANDROID_SDK_ROOT: $ANDROID_SDK_ROOT"

      - name: Validate SDK Installation
        run: |
          source $GITHUB_ENV
          sdkmanager --list

      - name: Install Emulator and System Images
        run: |
          sdkmanager --update
          sdkmanager --verbose "system-images;android-30;google_apis;x86_64" "platforms;android-30" "platform-tools" "emulator"

      - name: Debug SDK Directories
        run: |
          echo "Checking full SDK directory..."
          ls -R $ANDROID_SDK_ROOT || echo "SDK directory not found"
          echo "Checking system-images directory..."
          ls -R $ANDROID_SDK_ROOT/system-images || echo "System images directory not found"

      - name: Validate Installed System Images After Reinstall
        run: |
          sdkmanager --list | grep "system-images"
          ls -R $ANDROID_SDK_ROOT/system-images || echo "System images directory still not found"

      - name: Set up Android Emulator
        run: |
          source $GITHUB_ENV
          echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          nohup emulator -avd test -no-audio -no-window -gpu swiftshader_indirect &
          timeout 120s adb wait-for-device

      - name: Run Android Integration Tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart --device-id=emulator-5554
