name: Integration Tests with Dockerized Emulator

on:
  pull_request:
    branches:
      - ntrujillo/main
  workflow_dispatch:

jobs:
  android-tests:
    name: Run Android Integration Tests in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0

      - name: Install dependencies
        run: flutter pub get

      # Bloque para loguearse en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: nicolas3570
          password: 8q2ZRS[8+xB?

      - name: Start Android Emulator in Docker
        run: |
          echo "Starting Docker container with Android emulator..."
          docker run -d -p 6080:6080 --name android-container budtmo/docker-android-x86-8.1
          echo "Waiting for emulator to start..."
          sleep 30
          docker exec -it android-container start-emulator

      - name: Debug Emulator State
        run: |
          echo "Checking emulator logs..."
          docker logs android-container

      - name: Connect ADB to Emulator
        run: |
          echo "Connecting adb to emulator..."
          adb connect localhost:5555
          adb devices

      - name: Run Android Integration Tests
        run: |
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
