name: Integration Tests with Dockerized Emulator

on:
  pull_request:
    branches:
      - ntrujillo/main
  workflow_dispatch:

jobs:
  android-tests:
    name: Run Android Integration Tests with CircleCI Android Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 2.10.0

      - name: Install dependencies
        run: flutter pub get

      - name: Start Docker Container with CircleCI Android Image
        run: |
          echo "Starting Docker container with CircleCI Android image..."
          docker run -d --name android-container circleci/android:api-30 tail -f /dev/null
          echo "Docker container started."

      - name: Set up Android Emulator in Container
        run: |
          echo "Setting up Android emulator..."
          docker exec -i android-container sdkmanager "system-images;android-30;google_apis;x86_64" "platforms;android-30" "platform-tools" "emulator"
          docker exec -i android-container avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "pixel"
          docker exec -i android-container emulator -avd test -no-audio -no-window -gpu swiftshader_indirect &
          echo "Emulator is starting..."
          sleep 30

      - name: Connect ADB to Emulator
        run: |
          echo "Connecting adb to emulator..."
          adb connect localhost:5555
          adb devices

      - name: Run Android Integration Tests
        run: |
          flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
